export {
  getLineColor,
  getLineCssProps,
  getLineInlineStyles,
  getLineDarkReadableStyles,
  hardOutlineTextShadow,
  hardOutlineBoxShadow,
  normalizeLineId,
  getSeverityCategory,
  getSeverityClasses,
  getAccessibleSeverityLabel,
  sortLinesBySeverityAndOrder,
  getLineStatusSummary,
  getStatusKind,
  getWorstCurrentStatus,
  getCurrentLineStatuses,
  isNormalService,
  isScheduledClosure,
  hasNightService,
  getLineAriaLabel,
  getLineDisplayName,
  LINE_COLORS,
  LINE_DARK_TEXT_STROKE_WIDTH_PX,
  SEVERITY_MAPPING,
  LINE_ORDER,
  STATUS_KIND_ORDER,
} from './utils/ui';
export type {
  LineDarkContrastMode,
  LineDarkContrastOptions,
  LineDarkReadableStyles,
  StatusKind,
  LineStatusLike,
  CurrentStatusOptions,
  LineId,
  LineColorInfo,
  SeverityCategory,
  SeverityMapping,
} from './utils/ui';
